server:
  port: 8888

spring:
  application:
    name: config-server # Service name for Eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/your-username/lumadesk-config.git # If repo is private, add username/password or token

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/