server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Enables routing like "lb://auth-service"
    config:
      enabled: false

      routes: []

springdoc:
  swagger-ui:
    urls-primary-name: "LumaDesk-microservices"
  api-docs:
    groups:
      enabled: true