server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
      register-with-eureka: true

spring:
  application:
    name: api-gateway
    secret-key: lumadesk_secret_key_which_is_long_enough_12387614876192834769817364987162389476238974689237658976293846
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: auth_service_route
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**, /auth-service/v3/api-docs/**,/auth-service/swagger-ui/**,/auth-service/swagger-ui.html
            - id: user_service_route
              uri: lb://user-service
              predicates:
                - Path=/api/users/**, /user-service/v3/api-docs/**,/user-service/swagger-ui/**,/user-service/swagger-ui.html
            - id: ticket_service_route
              uri: lb://ticket-service
              predicates:
                - Path=/api/tickets/**, /api/tickets/raise-tickets/**,/api/sla/**,/api/issue-categories/**,/ticket-service/v3/api-docs/**,/ticket-service/swagger-ui/**,/ticket-service/swagger-ui.html
            - id: ai_agent_service_route
              uri: lb://ai-agent-service
              predicates:
                - Path=/api/ai-agent/**, /ai-agent-service/v3/api-docs/**,/ai-agent-service/swagger-ui/**,/ai-agent-service/swagger-ui.html
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Headers, RETAIN_UNIQUE

management:
  endpoints:
    web:
      exposure:
        include: "*"
  gateway:
    enabled: true

springdoc: #Swagger directly hits the microservice, not through API Gateway
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /auth-service/v3/api-docs
      - name: user-service
        url: /user-service/v3/api-docs
      - name: ticket-service
        url: /ticket-service/v3/api-docs
      - name: feedback-service
        url: /feedback-service/v3/api-docs
      - name: notification-service
        url: /notification-service/v3/api-docs
      - name: analytics-service
        url: /analytics-service/v3/api-docs
      - name: ai-agent-service
        url: /ai-agent-service/v3/api-docs
